addition of gan timer management
Nogesma/cube-bot-web pull request #2
Opened 2023-10-30 13:37 UTC by raphchta

I didn't style the button

2023-10-31 09:12 UTC, Nogesma requested changes
Thanks for the PR, I added some feedback.

You will also need to squash your commits before the merge can happen.

2023-10-31 09:12 UTC, Nogesma commented on package-lock.json
Remove this file, this is generated by npm. This project is using yarn.

2023-10-31 09:12 UTC, Nogesma commented on package.json
For Svelte projects, all dependencies should be dev-dependencies. 
`yarn remove rxjs && yarn add -D rxjs`

2023-10-31 09:12 UTC, Nogesma commented on src/tools/ganBluetooth.ts
I think this should be removed and the `gan-web-bluetooth` package should be used
`yarn add -D gan-web-bluetooth`

2023-10-31 09:12 UTC, Nogesma commented on src/lib/Navbar.svelte
This does not need to be modified

2023-10-31 09:12 UTC, Nogesma commented on src/routes/Solve.svelte
This does not need to be modified

2023-10-31 09:12 UTC, Nogesma commented on src/lib/Timer.svelte
The timer connection should probably happen in the settings page. I will do it myself unless you want to.

2023-11-03 22:37 UTC, raphchta commented on src/lib/Timer.svelte
no thank you for doing it

2023-11-03 22:41 UTC, raphchta commented on package.json
if I do npm remove rxjs && npm add -D rxjs. his walk?

2023-11-03 23:58 UTC, Nogesma commented on package.json
Yes, but please remove the package-lock.json generated by npm, and regenerate the yarn.lock by running `yarn`

2023-11-04 08:48 UTC, closed without merging